### PR TITLE
perf: optimize walk iterator

### LINKED ISSUE #2: Optimize file system walking
Right now we use [`walkDirRec`](https://nim-lang.org/docs/os.html#walkDirRec.i,string) which traverses recursively into directories automatically. This means `glob` potentially walks over a lot of files that the given pattern might completely ignore. Instead it should probably use [`walkDir`](https://nim-lang.org/docs/os.html#walkDir.i,string) so that we can decide whether to recurse into the directories as we come across them.

### PR DESCRIPTION
**Pull request by citycide**
Closes #2 

This should already eliminate unnecessary directory traversals but before merging I'd like to have a clear before & after. Reviews would be appreciated in the meantime.

### CODE REVIEW

**Comment by citycide** [comment]
I ran a comparison using this script:

https://gist.github.com/citycide/8884d5bb845c782e71fd5fa72783afa7

It creates a file structure with a bunch of nested directories & files (using some procs I pulled from our test file), and then uses the glob pattern `*.nim` which is a shallow match of any files with a `.nim` extension in the current directory. This means we can't possibly match files in sub-directories, so we shouldn't even enter them.

| branch                | time taken        | files walked    |
| --------------------- | ----------------- | --------------- |
| Unoptimized (master)  | 0.035885          | 410             |
| Optimized (perf-walk) | 0.001273          | 15              |

:tada:

**Comment by data-man** [comment]
For *nix you can use ```ftw```. I'm sure it will be faster.

**Comment by data-man** [comment]
There is cool Rust library: [walkdir](https://github.com/BurntSushi/walkdir).
For the ideas. :)

**Comment by citycide** [comment]
@data-man would that really be a perf gain over the stdlib `walkDir` implementation? Why wouldn't `ftw` be used there, and should it?

**Comment by data-man** [comment]
@citycide 
I don't know.
I'm study Nim for less than a year, and *nix a bit longer. I'm former Windows user. :)

Maybe, ```ftw``` isn't available on all kernels, libs, etc..

**Comment by citycide** [comment]
Got it &mdash; I'll look more into `ftw` but I'll merge this as is. Can always do more down the road :smile:

**Comment by data-man** [comment]
BTW maybe ```pathMatches``` from PR [Add os.pathMatches proc](https://github.com/nim-lang/Nim/pull/7836) will be useful for you.

**Comment by citycide** [comment]
@data-man not sure that API would be useful in `glob` because Windows' `PathMatchSpec` only supports a very limited subset of the features involved here, I think just `*` and `?` wildcard matching. The goal of this library though is to provide all the posix features on all platforms, including extended features like `{a,b}` groups, `[ab]` character classes, and `?()`/`@()` etc pattern matching.

**Comment by data-man** [comment]
@citycide 

Maybe something like ```useNativeMatch``` can be faster. :)

**Pull request merged**
