### PR TITLE
update regex dependency now that https://github.com/nitely/nim-regex/issues/83 was fixed

### PR DESCRIPTION
**Pull request by timotheecour**
/cc @citycide 
refs https://github.com/nitely/nim-regex/issues/83

@nitely could you please tag a release in nim-regex to unblock this PR?

### CODE REVIEW

**Comment by nitely** [comment]
> @nitely could you please tag a release in nim-regex to unblock this PR?

Yeah, I just did it.

**Review by citycide — APPROVED** [review]
LGTM, thanks for reporting upstream.

**Comment by squattingmonk** [comment]
Any plans to tag a new version of glob or at least update the `0.9.0` tag? `0.9.0` still recognizes `regex 0.17.0` as fulfilling the dependency. Current work-around is to install `glob@#head`.

**Comment by timotheecour** [comment]
committed https://github.com/citycide/glob/commit/f484a8792b8df2345399cea03b961057171da0b7 but I'll let @citycide create a git tag

**Comment by citycide** [comment]
I'll get at that this weekend (maybe tonight), thanks for the ping.

**Pull request merged**
